### ISSUE TITLE
OOXML extensions

### ISSUE THREAD

**Issue by RvanVeenendaal** [opf-labs/sheets-preservation-spec#16]
Under 4.2, OOXML, of the specification, the extensions for ODS are used. 
This should probably be updated to reflect the OOXML extensions (XLSX).
Probably not XLSM, as we don't want macros.
See 4.2: ODS_3 | Extension | The file MUST have extension “.fods”, “.ods” or “ots”.

**Comment by Asbjoedt** [comment]
You are right. I send in a fix. Regarding the macros, we should take that discussion separately in https://github.com/opf-labs/sheets-preservation-spec/issues/19. Therefore, this fix will keep the macro extensions in, and we may later remove depending on the macro discussion.
