### ISSUE TITLE
OOXML ids

### ISSUE THREAD

**Issue by RvanVeenendaal** [opf-labs/sheets-preservation-spec#17]
Under [4.2](https://github.com/opf-labs/sheets-preservation-spec/blob/main/v1.0/Specification.md#42-office-open-xml-spreadsheetml) of this specification, the IDs for OOXML use the ODS ids from the ODS table above it. Wouldn't it be better to change them into OOXML ids?

**Comment by Asbjoedt** [comment]
You are right, I send in a fix.
